project:
  type: website
website:
  title: "My Research Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Contact"
        href: contact.qmd
format:
  html:
    theme: cosmo  # Other options: flatly, spacelab, etc.
    css: styles.css  # Optional custom styles

editor: visual

