project:
  type: website
website:
  title: "Fred J Pasquarella"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Presentations"
        href: presentations.qmd
      - text: "Contact"
        href: contact.qmd
format:
  html:
    theme: yeti  # Other options i like: cosmo, flatly, spacelab
    css: styles.css  # Optional custom styles

editor: visual

