---
title: "Presentations"
toc: true
toc-depth: 2
toc-location: right
---

# 游닉 Professional Presentations

:::: {.grid .g-4}

::: {.g-col-6}
::: {.card}
### **Navigating Telemental Health: Provider Perceptions and Decision-Making**  
游늯 **Poster | SSWR 2025 | Seattle, WA**  
游논 *Pasquarella, F. J., Aubry, A., Berger, S., Drake, B., Patel, P., Schueler, C., & Lee, S.*  
游늯 [View Presentation](assets/presentations/sswr_2025_tmh_perceptions.pdf){target="_blank"}
:::
:::

::: {.g-col-6}
::: {.card}
### **Analyzing Telemental Health Service Modality Effects on Engagement**  
游늯 **Paper | SSWR 2025 | Seattle, WA**  
游논 *Pasquarella, F. J., Aubry, A., Berger, S., Drake, B., Patel, P., Schueler, C., & Lee, S.*  
游늯 [View Presentation](assets/presentations/sswr_2025_tmh_engagement.pdf){target="_blank"}
:::
:::

::: {.g-col-6}
::: {.card}
### **The Catch-22 of Telehealth: A Qualitative Study on Work & Well-being**  
游늯 **Poster | SSWR 2025 | Seattle, WA**  
游논 *Lizano, E., Bergen, C., Kay, B., Pasquarella, F. J., & Lee, S.*  
游늯 [View Presentation](assets/presentations/sswr_2025_qualitative_telehealth.pdf){target="_blank"}
:::
:::

::: {.g-col-6}
::: {.card}
### **Intersection of Evaluation and Data Analytics: A Community Case Study**

游늯 **Poster | AEA 2024 | Portland, OR**  
游논 *Lee, S. & Pasquarella, F. J.*  
游늯 [View Presentation](assets/presentations/aea_2024_data_science_eval.pdf){target="_blank"}
:::
:::

::: {.g-col-6}
::: {.card}
### **Impact of Trauma-Informed Care Training in Community Mental Health**  
游늯 **Poster | SSWR 2024 | Washington, D.C.**  
游논 *Pasquarella, F. J., Cunningham, B., Der Sarkissian, A., Gonzalez, S., Salamat, M., Makanui, K., Miller, S., Lee, S.*  
游늯 [View Presentation](assets/presentations/sswr_2024_tic_training.pdf){target="_blank"}
:::
:::

::: {.g-col-6}
::: {.card}
### **Tale of Two Stories: Staff & Resident Experiences in Crisis Treatment**  
游늯 **Poster | AEA 2023 | Indianapolis, IN**  
游논 *Lee, S., Pasquarella, F. J., Lee, G., & Humble, J.*  
游늯 [View Presentation](assets/presentations/aea_2023_crt_eval.pdf){target="_blank"}
:::
:::

::: {.g-col-6}
::: {.card}
### **Planning and Implementing and Organizational Health Assessment at a Community Mental Health Center**  
游늯 **Paper | SSWR 2023 | Phoenix, AZ**  
游논 *Lee, S., Pasquarella, F. J., De La Peza, D., Lizano, E. L., & Santoro, K.*  
游늯 [View Presentation](assets/presentations/sswr_2023_org_health_assessment.pdf){target="_blank"}
:::
:::

::: {.g-col-6}
::: {.card}
### **From Room to Zoom: Evaluating the Implementation and Use of Telehealth Services**  
游늯 **Paper | AEA 2022 | New Orleans, LA**
游논 *Lee, S., Pasquarella, F. J., & Harwood, M.*
游늯 [View Presentation](assets/presentations/aea_2022_telehealth_eval.pdf){target="_blank"}
:::
:::

:::: 


# 九勇 Academic Presentations

Pasquarella, F. J., & Johnson, G. L. (April, 2015). [Structural Equation Model of Political Instability, Religiosity, and Progressive Values](assets/presentation/wpa_2015_politics_religion.pdf){target="_blank"}. Poster presented at Western Psychological Association's 95th Annual Convention, Las Vegas, NV.

Pasquarella, F. J., & Preston, K. (April, 2015). Reliability Differences Between Response Formats of Rotter's Locus of Control. Poster presented at Western Psychological Association's 95th Annual Convention, Las Vegas, NV.

Pasquarella, F. J., & Miller, A. (2012). Give Me a Clue: A Curious Study. Poster presented at SACNAS National Research Conference, Seattle, WA.

Miller, A., & Pasquarella, F. J., (2012). Give Me a Clue: A Curious Study. Paper presented at California State University 26th Annual Statewide Student Research Competition, Long Beach, CA.

Pasquarella, F. J. (2012). Predicting Suicidal Behaviors Among the Youth. Poster presented at California State University, Dominguez Hills Research Showcase at the Presidential and Premiere Scholarship Competition, Carson, CA.
