---
title: "Research"
---

My research focuses on the intersection of mental health service delivery, workforce engagement, and systemic challenges in community-based mental health settings. Through a blend of applied research and theoretical exploration, I seek to improve service provision, enhance workforce well-being, and contribute to a deeper understanding of societal and psychological phenomena. I am committed to producing data-driven solutions that support mental health providers and strengthen the communities they serve.

# Publications

### [Telemental health and remote work: An exploratory analysis of their dual impact on mental health professionals' experiences during COVID-19 stay-at-home orders](https://link.springer.com/article/10.1007/s11414-024-09925-z){target="_blank"}

**2025** \*Lizano, E. L., Bergen, C., Smith, B., Pasquarella, F. J., & Lee, S.

**Abstract**: Rapid shifts in modes of mental health service delivery, for example from in-person to telehealth, profoundly impact mental health workers, particularly those providing services for at-risk populations in community mental health (CMH) settings. The COVID-19 pandemic offered a unique opportunity to examine the impacts of one such transition, as CMH agencies were compelled to adopt telemental health services abruptly due to mandatory stay-at-home orders. This study examines the experiences of CMH workers during the emergency transition to remote work and telemental health services in 2020 at a large CMH agency in California. Seven months after the emergency transition to remote work, one hundred and twelve providers and staff members submitted written responses to open-ended self-report questions about the impacts of remote work and the transition to telemental health on their professional and personal lives. A team of five researchers analyzed these data using content analysis. Findings underscore the dual nature of the shift to remote work and telemental health, exposing specific positive and negative impacts. Three categories of themes are identified and analyzed: structural changes, impact on employees, and impact on clinical care. Multiple themes are identified and explored within these categories, including work environment, productivity, and emotional well-being. Understanding CMH workers' needs and experiences during the transition to remote work and telemental health is critical to ensuring provider well-being and service quality. Building on these insights, tailored strategies can be developed to support the CMH workforce better during future periods of transition in modes of mental health service delivery.

### [Follow-up Care Offers and Acceptance in Crisis Line Suicide Prevention Services](https://psycnet.apa.org/record/2025-25194-001){target="_blank"}

**2024** *Fulginiti, A., Doyle, M., Miller, S., Lee, S., & Pasquarella, F. J.*

**Abstract**: *Background:* Prior work has explored the impact of follow-up calls in a crisis line context, but no research has investigated the offer and acceptance of follow-up care. *Aims:* To identify caller/call characteristics associated with whether a caller is offered and accepts follow-up services. *Methods:* This cross-sectional study included data from 55,594 callers to a member center of the 988 Suicide & Crisis Lifeline (988) between 2017 and 2019. Logistic regression analyses were conducted to examine associations between caller/call characteristics and two follow-up outcomes. *Results:* Black callers and those with higher suicide capability and intent had greater odds of being offered and accepting follow-up. Longer call duration was also associated with higher odds of being offered and accepting follow-up. Higher suicidal desire uniquely increased the odds of offers, whereas a higher level of buffers uniquely decreased the odds of offers. *Limitations:* Data were collected from a single 988-member center and cannot be generalized. *Conclusions:* That one-third of callers do not accept follow-up highlights the need to understand reasons for not accepting follow-up. That callers with higher risk profiles are offered and accept follow-up at higher rates is reassuring and underscores the benefit of tailoring follow-up interventions for higher-risk callers.

### [Planning and Implementing an Organizational Health Assessment in a Community Mental Health Setting](https://link.springer.com/article/10.1007/s10597-022-01052-3){target="_blank"}

**2022** *Lee, S., Pasquarella, F. J., De La Peza, D., Lizano, E. L., & Santoro, K.*

**Abstract**: The workforce is the essential driver behind mental health service provision and the most valuable asset to any community mental health organization. To build and retain a stable and healthy workforce, systematic recruitment and retention strategies are needed. An organizational health assessment is a valuable tool in developing targeted organizational interventions to create a positive work environment and retain an engaged workforce. Starting in 2017, a large community mental health organization in Southern California implemented such an assessment to drive actionable steps to improve employee experience and decrease turnover. This case study describes the development and implementation of a low-cost organizational health assessment through five phases: development of the assessment, data collection, analysis, metrics and data visualization, and dissemination of findings and development of interventions. Key lessons learned include the importance of utilizing the findings and achieving staff and leadership buy-in.

### [An Examination of Work Engagement's Antecedents and Consequences in a Sample of U.S. Community Mental Health Providers](https://onlinelibrary.wiley.com/doi/abs/10.1111/hsc.13670){target="_blank"}

**2021** *Pasquarella, F. J., Lizano, E. L., Lee, S., & De La Peza, D.*

**Abstract**: The study examined the relationship between job demands and resources, work engagement, and turnover intentions in a community mental health context. Using path analysis, we tested a conceptual model where we hypothesized that job demands (pressure to produce and role ambiguity) had a negative relationship to work engagement (H1) and resources (team commitment, supervisor relationship, and connection to organizational mission) were positively related to engagement (H2). Furthermore, greater engagement would be related to lower intention to leave the job (H3). Additionally, we hypothesized that there was an indirect effect of job demands and resources on turnover intention mediated via engagement (H4). The study used cross-sectional data collected in 2018 from a sample of N = 170 mental health providers employed in a community mental health center in the Southwest region of the United States. The study findings suggest that the job demands tested, pressure to produce and role ambiguity, were negatively related to engagement (H1). Of the job resources tested, only team commitment and connection to mission were positively related to engagement (H2). Work engagement was negatively related to intention to leave (H3). There were indirect effects of job demands and job resources (pressure to produce, role ambiguity and connection to the organization mission) on intention to leave mediated through engagement (H4). The findings suggest that managers and administrators in community mental health organizations may help promote a more stable workforce by bolstering the resources that lead to greater work engagement and mitigating the job demands that reduce engagement.

### [Managing Substance Use for Client with Serious Mental Illness: Knowledge, Attitude, and Training Challenges Among Outpatient Behavioral Health Providers in California, Ohio, and New York](https://www.sciencedirect.com/science/article/pii/S0740547221002737){target="_blank"}

**2021** *Kelly, E., Pasquarella, F. J., Davis, L., Hunt, A., Lee, S., Fairhurst, S., ... Brekke, J. S.*

**Abstract**: *Purpose:* Individuals with serious mental illness have high rates of substance use. The most commonly used substances among this population are alcohol and cannabis, and whether clinical providers delivering mental health services feel adequately prepared to address substance use is unclear. While information about the effects of alcohol are well established, the effects of cannabis are less well known and staff may feel less confident in their abilities to assess its use and may rely on more informal sources to learn about it. *Methods:* Mental health agencies in three states (California, Ohio, and New York) surveyed their staff (n =717) to explore their knowledge, training, and expertise in assessment of substance use generally as well as cannabis and alcohol specifically. *Results:* Overall, providers felt more prepared to address their clients' alcohol use than cannabis use. In between-state comparisons, California providers felt significantly less well prepared to assess, discuss, and refer their clients to treatment compared to Ohio and New York providers. Using a series of multi-categorical mediation models, we confirmed that deficits in training for these specific substances largely accounted for between-state differences in assessment, capacity, and treatment. *Conclusions:* Substance use training to address the service needs of individuals with co-occurring disorders is insufficient and a significant need exists for systemic changes to workforce training of community mental health providers.

# Graduate Research

## Master's Thesis

### [The Construction and Validation of the Fullerton Ontological Confusion Scale](assets/papers/2015_thesis.pdf){target="_blank"}

*Pasquarella, F. J.*

**Abstract**: The Fullerton Ontological Confusion (FOC) scale was constructed to address the issues of inconsistent theory and inadequate measurement regarding paranormal, superstitious, magical, and supernatural (PSMS) beliefs. For the FOC scale, PSMS beliefs were defined as confusions of ontology, or the misattribution of core knowledge belief categories. The FOC was empirically evaluated under an Item Response Theory framework using the nominal response model (NRM) to estimate item parameters and the Wald test to evaluate within-item category variation. Using the NRM and the Wald test, the FOC scale items were revised to yield a measure that was optimally formatted and informative. Correlational analysis was used to validate the FOC scale by testing the hypothesized relationships to theoretically related and unrelated constructs. The FOC scale was found to have a good degree of validity with most of the testable validation hypotheses being supported. Compared to the available existing measures, the FOC scale could be used as a more pure and informative measure for PSMS beliefs.

## Other Research

### [A Structural Equation Model of Political Instability, Religiosity, and Progressive Values](assets/papers/2015_politics_religion.pdf){target="_blank"}

*Pasquarella, F. J. & Johnson, G. L.*

**Abstract**:A great deal of evidence supports the theory that political instability and religiosity are positively correlated. Moreover, religiosity has been shown to be positively related to progressive social values. No current research addresses the causal relationship between all three constructs. This paper proposes a model of complete mediation in which political instability is related to progressive values strictly through religiosity viz. increases in political instability are associated with decreases in progressive values through increases in religiosity. A structural equation model was created to confirm this hypothesis using randomly sampled data from the 2005 World Values Survey (N = 3,881). Exploratory factor analyses found that indicators for the latent factors were satisfactory. The hypothesized model was found to have poor fit. A three-factor EFA with oblique rotation indicated the presence of separate factors within Progressiveness. A revised model was tested with only Gender Equality as a form of Progressiveness. The new model attained satisfactory fit to the data. The estimated parameters fit the proposed theory with two exceptions: greater political instability was associated with lower religiosity, and the direct effect of religiosity on gender equality was quite weak. Limitations included systematic missing data, unrepresentative country proportions in the sample data, and the agglomeration of religious denominations into one measure of religiosity. Future research should utilize a more objective measure of Political Instability and attempt to look at between-country differences in the mediation model. Based on the estimated parameters, a direct feedback loop between religiosity and political instability should also be investigated.
